import pet_accessories from "./images/accessories/pet_accessories.jpg";


const petAccessories = [
  {
    _id: 1,
    name: "Dog Collar",
    image: pet_accessories ,
    description: "A stylish and durable collar for your furry friend.",
    species: "Dog",
    category: "Collars",
    price: 12.99,
    availability: 50,
    rating: 4.5,
    numReviews: 25,
  },
  {
    _id: 2,
    name: "Cat Toys Set",
    image: pet_accessories ,
    description: "A set of interactive toys to keep your cat entertained.",
    species: "Cat",
    category: "Toys",
    price: 9.99,
    availability: 40,
    rating: 4.8,
    numReviews: 30,
  },
  {
    _id: 3,
    name: "Fish Tank",
    image: pet_accessories ,
    description: "Colorful decorations to enhance your aquarium's beauty.",
    species: "Fish",
    category: "Decorations",
    price: 7.99,
    availability: 60,
    rating: 4.3,
    numReviews: 20,
  },
   {
    _id: 4,
    name: "Fish Tank",
    image: pet_accessories ,
    description: "Colorful decorations to enhance your aquarium's beauty.",
    species: "Fish",
    category: "Decorations",
    price: 7.99,
    availability: 60,
    rating: 4.3,
    numReviews: 20,
  },
   {
    _id: 5,
    name: "Fish Tank",
    image: pet_accessories ,
    description: "Colorful decorations to enhance your aquarium's beauty.",
    species: "Fish",
    category: "Decorations",
    price: 7.99,
    availability: 60,
    rating: 4.3,
    numReviews: 20,
  },
   {
    _id: 6,
    name: "Fish Tank",
    image: pet_accessories ,
    description: "Colorful decorations to enhance your aquarium's beauty.",
    species: "Fish",
    category: "Decorations",
    price: 7.99,
    availability: 60,
    rating: 4.3,
    numReviews: 20,
  },
  // Add more pet accessory objects as needed
];

export default petAccessories;
