import cat1 from "../images/cats/cat1.jpg";
import cat2 from "../images/cats/cat2.jpg";
import cat3 from "../images/cats/cat3.jpeg";

const cats = [
  {
    _id: 1,
    name: "Whiskers",
    type: "cat",
    image: cat1,
    description: "Munchkin cats are famous for their endearing appearance",
    species: "Munchkin",
    category: "Pets",
    price: 50.99,
    availability: 10,
    rating: 4.0,
    numReviews: 15,
  },
  {
    _id: 2,
    name: "Mittens",
    type: "cat",
    image: cat2,
    description: "A cute kitten with soft paws and a curious nature.",
    species: "Domestic Cat",
    category: "Pets",
    price: 45.99,
    availability: 5,
    rating: 4.0,
    numReviews: 10,
  },
  {
    _id: 3,
    name: "Leo",
    type: "cat",
    image: cat3,
    description: "A regal and majestic lion with a luxurious mane.",
    species: "Lion",
    category: "Wild Animals",
    price: 199.99,
    availability: 2,
    rating: 4.8,
    numReviews: 20,
  },
   {
    _id: 4,
    name: "Leo",
    type: "cat",
    image: cat3,
    description: "A regal and majestic lion with a luxurious mane.",
    species: "Lion",
    category: "Wild Animals",
    price: 199.99,
    availability: 2,
    rating: 4.8,
    numReviews: 20,
  },
     {
    _id: 5,
    name: "Leo",
    type: "cat",
    image: cat3,
    description: "A regal and majestic lion with a luxurious mane.",
    species: "Lion",
    category: "Wild Animals",
    price: 199.99,
    availability: 2,
    rating: 4.8,
    numReviews: 20,
  },
     {
    _id: 6,
    name: "Leo",
    type: "cat",
    image: cat3,
    description: "A regal and majestic lion with a luxurious mane.",
    species: "Lion",
    category: "Wild Animals",
    price: 199.99,
    availability: 2,
    rating: 4.8,
    numReviews: 20,
  },
   {
    _id: 7,
    name: "Whiskers",
    type: "cat",
    image: cat1,
    description: "Munchkin cats are famous for their endearing appearance",
    species: "Munchkin",
    category: "Pets",
    price: 50.99,
    availability: 10,
    rating: 4.5,
    numReviews: 15,
  },
   {
    _id: 8,
    name: "Whiskers",
    type: "cat",
    image: cat1,
    description: "Munchkin cats are famous for their endearing appearance",
    species: "Munchkin",
    category: "Pets",
    price: 50.99,
    availability: 10,
    rating: 4.5,
    numReviews: 15,
  },
  
  // Add more cat objects as needed
];

export default cats;
