
import petfood2 from "../images/petfoods/petfood2.jpg";



const petFoods = [
  {
    _id: 1,
    name: "Premium Dog Food",
    type: "petfood",
    image: petfood2,
    description: "High-quality dog food with a balanced blend of nutrients.",
    species: "Dog",
    category: "Dog Food",
    price: 24.99,
    availability: 100,
    rating: 4.7,
    numReviews: 50,
  },
 {
    _id: 2,
    name: "Tropical Fish Flakes",
    type: "petfood",
    image: petfood2,
    description: "Colorful fish flakes that provide essential nutrition to aquarium fish.",
    species: "Fish",
    category: "Fish Food",
    price: 8.99,
    availability: 120,
    rating: 4.4,
    numReviews: 35,
  },
  {
    _id: 3,
    name: "Tropical Fish Flakes",
    type: "petfood",
    image: petfood2,
    description: "Colorful fish flakes that provide essential nutrition to aquarium fish.",
    species: "Fish",
    category: "Fish Food",
    price: 8.99,
    availability: 120,
    rating: 4.4,
    numReviews: 35,
  },
    {
    _id: 4,
    name: "Tropical Fish Flakes",
    type: "petfood",
    image: petfood2,
    description: "Colorful fish flakes that provide essential nutrition to aquarium fish.",
    species: "Fish",
    category: "Fish Food",
    price: 8.99,
    availability: 120,
    rating: 4.4,
    numReviews: 35,
  },
    {
    _id: 5,
    name: "Tropical Fish Flakes",
    type: "petfood",
    image: petfood2,
    description: "Colorful fish flakes that provide essential nutrition to aquarium fish.",
    species: "Fish",
    category: "Fish Food",
    price: 8.99,
    availability: 120,
    rating: 4.4,
    numReviews: 35,
  },
    {
    _id: 6,
    name: "Tropical Fish Flakes",
    type: "petfood",
    image: petfood2,
    description: "Colorful fish flakes that provide essential nutrition to aquarium fish.",
    species: "Fish",
    category: "Fish Food",
    price: 8.99,
    availability: 120,
    rating: 4.4,
    numReviews: 35,
  },
      {
    _id: 7,
    name: "Tropical Fish Flakes",
    type: "petfood",
    image: petfood2,
    description: "Colorful fish flakes that provide essential nutrition to aquarium fish.",
    species: "Fish",
    category: "Fish Food",
    price: 8.99,
    availability: 120,
    rating: 4.4,
    numReviews: 35,
  },
      {
    _id: 8,
    name: "Tropical Fish Flakes",
    type: "petfood",
    image: petfood2,
    description: "Colorful fish flakes that provide essential nutrition to aquarium fish.",
    species: "Fish",
    category: "Fish Food",
    price: 8.99,
    availability: 120,
    rating: 4.4,
    numReviews: 35,
  },




  // Add more pet food objects as needed
];

export default petFoods;
