import fish2 from "./images/fishes/fish2.jpeg";
import fish3 from "./images/fishes/fish3.jpg";
import fish4 from "./images/fishes/fish4.jpeg";

const fishes = [
  {
    _id: 1,
    name: "Goldfish",
    image: fish2,
    description: "A small and colorful fish often kept as a pet in aquariums.",
    species: "Carassius auratus",
    category: "Aquarium Fish",
    price: 5.99,
    availability: 50,
    rating: 4.3,
    numReviews: 25,
  },
  {
    _id: 2,
    name: "Salmon",
    image: fish3,
    description: "A delicious and nutritious fish known for its rich flavor.",
    species: "Salmo salar",
    category: "Seafood",
    price: 12.99,
    availability: 15,
    rating: 4.8,
    numReviews: 30,
  },
  {
    _id: 3,
    name: "Clownfish",
    image: fish4,
    description: "A small, vibrant fish famous for its appearance in animated movies.",
    species: "Amphiprioninae",
    category: "Aquarium Fish",
    price: 9.99,
    availability: 20,
    rating: 4.5,
    numReviews: 18,
  },
    {
    _id: 4,
    name: "Clownfish",
    image: fish4,
    description: "A small, vibrant fish famous for its appearance in animated movies.",
    species: "Amphiprioninae",
    category: "Aquarium Fish",
    price: 9.99,
    availability: 20,
    rating: 4.5,
    numReviews: 18,
  },
    {
    _id: 5,
    name: "Clownfish",
    image: fish4,
    description: "A small, vibrant fish famous for its appearance in animated movies.",
    species: "Amphiprioninae",
    category: "Aquarium Fish",
    price: 9.99,
    availability: 20,
    rating: 4.5,
    numReviews: 18,
  },
    {
    _id: 6,
    name: "Clownfish",
    image: fish4,
    description: "A small, vibrant fish famous for its appearance in animated movies.",
    species: "Amphiprioninae",
    category: "Aquarium Fish",
    price: 9.99,
    availability: 20,
    rating: 4.5,
    numReviews: 18,
  },
  // Add more fish objects as needed
];

export default fishes;
